#!/bin/bash

umount /.snapshots
rm -r /.snapshots

username="k2"

snapper -c root create-config /
snapper -c home create-config /home
snapper -c root set-config 'TIMELINE_CREATE=no'
snapper -c root set-config 'ALLOW_GROUPS='$username''
snapper -c root set-config 'SYNC_ACL=yes'
snapper -c home set-config 'TIMELINE_CREATE=no'
snapper -c home set-config 'ALLOW_GROUPS='$username''
snapper -c home set-config 'SYNC_ACL=yes'
sed -i 's/^TIMELINE_LIMIT_HOURLY="10"/TIMELINE_LIMIT_HOURLY="5"/i' /etc/snapper/configs/root
sed -i 's/^TIMELINE_LIMIT_DAILY="10"/TIMELINE_LIMIT_DAILY="7"/i' /etc/snapper/configs/root
sed -i 's/^TIMELINE_LIMIT_MONTHLY="10"/TIMELINE_LIMIT_MONTHLY="0"/i' /etc/snapper/configs/root
sed -i 's/^TIMELINE_LIMIT_YEARLY="10"/TIMELINE_LIMIT_YEARLY="0"/i' /etc/snapper/configs/root
sed -i 's/^TIMELINE_LIMIT_HOURLY="10"/TIMELINE_LIMIT_HOURLY="5"/i' /etc/snapper/configs/home
sed -i 's/^TIMELINE_LIMIT_DAILY="10"/TIMELINE_LIMIT_DAILY="7"/i' /etc/snapper/configs/home
sed -i 's/^TIMELINE_LIMIT_MONTHLY="10"/TIMELINE_LIMIT_MONTHLY="0"/i' /etc/snapper/configs/home
sed -i 's/^TIMELINE_LIMIT_YEARLY="10"/TIMELINE_LIMIT_YEARLY="0"/i' /etc/snapper/configs/home

btrfs su del /.snapshots/
mkdir /.snapshots
mount -av

#for snapper rollback / boot with the snapshot from grub / do snapper --ambit classic rollback x/
#boot with the writable snapshot created and do grub-install... and grub-mkconfig .../ reboot and its done!
