#!/bin/bash


abort() {
    echo >&2 "$0 ERROR: $@"
    exit 1
}

usercancel()
{ abort "user cancel."
}

passwcheck()
{
pw=''
cpw=''
type=$1

while [ $pw != $cpw ] ||  [ -z $pw ] ||  [ -z $cpw ]; do
	pw=$(dialog --insecure --passwordbox "enter $type password" 0 0 --output-fd 1) || usercancel
	cpw=$(dialog --insecure --passwordbox "confirm $type password" 0 0 --output-fd 1) || usercancel
done
}

starting()
{
dialog --msgbox "Disclaimer: READ THE SCRIPT CAREFULLY BEFORE USE IT.\n\n
ITS CURRENTLY IN DEVELOPMENT AND NOT FULLY TESTED.\n\n
USE IT AT YOUR OWN RESPONSABILITY.\n\n
Guidelines: \n
The disk will be erased. If needed, first make a backup in a external disk!\n
For BTRFS it will use all disk space to create btrfs subvolumes. \n
For XFS or EXT4, you can choose the size of partitions. Leave at the default (25G) and it will \n
create a home partition with the remaining disk space, or leave the field EMPTY, and it will \n
use all disk space to create the root partition.\n
For swap, if needed, use zramen.\n
For superuser, i use doas, sudo is uninstalled during install, also there is an option to disable root login.\n
Firewal nftables and apparmor are installed by default. \n
To enable secure boot with sbctl, you must set secure boot in uefi to setup mode.  \n
There is a lot of customization and some bugs...\n
Its easy to adapt to other preferences!! " 0 0 --output-fd 1

clear

dialog --yesno "Proceed to Void installation?" 0 0 --output-fd 1
start=$?
clear

if [[ $start == 1 ]]; then
	exit
fi



#uefi check
uefi=$(ls /sys/firmware/efi/efivars/)

if [[ ! -z $uefi ]]; then
	uefi="true"
	dialog --msgbox "UEFI FILE SYSTEM FOUND!!" 0 0 --output-fd 1
else
	dialog --msgbox "UEFI NOT FOUND! OLD COMPUTER..." 0 0 --output-fd 1
	uefi="false"
	#	exit
fi



keyb=$(dialog --radiolist "Choose your tty keyboard"  0 0 9 'pt' 1 on 'br-abnt' 2 off 'uk' 3 off 'us' 4 off  "ca" 5 off "it" 6 off "es" 7 off "de" 8 off "fr" 9 off --output-fd 1) || usercancel

#keyb=$(dialog --title "choose your keymap" --fselect /usr/share/kbd/keymaps/ 0 0 --output-fd 1)

 dialog --yesno "Disable root account? (yes/no)" 0 0 --output-fd 1
 adm=$?

if [[ $adm == 1 ]]; then

	passwcheck "root"
	root_pw=$pw
fi

while [ -z $username ]; do
	username=$(dialog --inputbox "Enter a username" 0 0 --output-fd 1) || usercancel
done

passwcheck "user"
user_pw=$pw

user_groups=$(dialog --checklist "Choose user groups" 0 0 10 'wheel' 1 on 'audio' 2 on 'video' 3 on 'kvm' 4 off \
'storage' 5 off 'network' 6 on 'xbuilder' 7 off 'plugdev' 8 off 'scanner' 9 off 'lp' 10 off --output-fd 1) || usercancel
user_groups="${user_groups// /,}"

diskname=$(lsblk -l -o NAME,TYPE | grep "disk" | tr -d ' \n')
diskname="${diskname//'disk'/ }"
disksize=$(lsblk $disk -l -o SIZE,TYPE | grep "disk")
disksize="${disksize// disk/}"

disk=$(dialog --backtitle "Disks detected are: $diskname" --radiolist "Enter disk for installation" 0 0 3 '/dev/sda' 1 on '/dev/vda' 2 off '/dev/nvme0n1' 3 off --output-fd 1) || usercancel

fs_type=$(dialog --radiolist "Choose the file system" 0 0 3 'xfs' 1 on 'ext4' 2 off 'btrfs' 3 off --output-fd 1) || usercancel

if [[ $uefi == "true" ]]; then
	while [ -z $boot_part_size ]; do
		boot_part_size=$(dialog --backtitle "Total disk size is: $disksize" --inputbox "Enter efi partition size (default: 512M)" 0 0 512M --output-fd 1) || usercancel
	done
fi

if [[ $fs_type == "btrfs" ]]; then
	root_part_size=""
else
	root_part_size=$(dialog --backtitle "Total disk size is: $disksize" --inputbox "Enter root partition size (default: 25G). If there is more space left, the remaining space will be use to create a home partition OR leave the field empty to create only a root partition with all disk space.)" 0 0 25G --output-fd 1) || usercancel
fi

hostname=$(dialog --inputbox "Enter a hostname" 0 0 xpto --output-fd 1) || usercancel

	glib=$(dialog --radiolist "Choose btw glibc or musl" 0 0 2 'glibc' 1 on 'musl' 2 off --output-fd 1 ) || usercancel

if [[ $glib == "glibc" ]]; then
	glib=""
fi

while [ $local == "/usr/share/zoneinfo/" ] || [ -z $lslocal ]; do

    local=$(dialog --backtitle "Use tab, arrow keys and spacebar to select and expand folders. example /usr/share/zoneinfo/Europe/Lisbon" --title "Choose your timezone" --fselect /usr/share/zoneinfo/ 0 0 --output-fd 1) || usercancel
	lslocal=$(ls $local)
done

language=$(dialog --radiolist "Choose your language" 0 0 7 'en_US.UTF-8' 1 off 'en_CA.UTF-8' 2 off 'en_IE.UTF-8' 3 off 'en_GB.UTF-8' 4 off \
'pt_PT.UTF-8' 5 off 'pt_BR.UTF-8' 6 off 'C.UTF-8' 7 on --output-fd 1) || usercancel


if [[ $uefi == "true" ]]; then
	bm=$(dialog --radiolist "choose your boot manager" 0 0 2 'grub' 1 on 'uki' 2 off  --output-fd 1) || usercancel
else
	bm="grub"
fi

graphical=$(dialog --radiolist "choose your graphical interface" 0 0 4 'kde' 1 on 'gnome' 2 off 'xfce' 3 off 'minimal' 4 off --output-fd 1) || usercancel


if [[ $uefi == "true" ]]; then
	dialog --yesno "enable secure boot?" 0 0 --output-fd 1
	secure_boot=$?

else
	secure_boot=1

fi
clear

ARCH="x86_64"

void_repo="https://repo-fastly.voidlinux.org/current"

if [[ $glib == "musl" ]]; then

	ARCH="x86_64-musl"
	void_repo="https://repo-fastly.voidlinux.org/current/musl"
fi


#after install change mirror with xmirror

#dns_list=("9.9.9.9" "1.1.1.1")

crm="chroot /mnt"

apps_base="nano elogind dbus chrony xmirror \
ufetch pipewire wireplumber vsv btop bat \
octoxbps flatpak zramen iwd lm_sensors"

apps_optional="hplip hplip-gui gparted"

apps_intel="mesa-dri mesa intel-ucode intel-gpu-tools intel-video-accel libva-utils"

if [[ $disk == "/dev/vda" ]]; then #virtual machine

	apps_intel="mesa-dri mesa"
	apps_optional=""
	apps_base="nano ufetch pipewire wireplumber vsv htop bat"
fi

apps_kde="kde-plasma kde-baseapps ffmpegthumbs discover spectacle \
flatpak-kcm kwalletmanager kcalc okular gwenview ark"

apps_gnome="gnome-core gnome-console gnome-tweaks gnome-browser-connector \
gnome-text-editor"

apps_xfce="xfce4 paper-gtk-theme paper-icon-theme lightdm xfce4-pulseaudio-plugin \
xfce4-whiskermenu-plugin labwc"

apps_office="libreoffice-writer libreoffice-calc"

apps_multimedia="vlc ffmpeg"

apps_browser="firefox"

apps_minimal="nano vsv opendoas iwd terminus-font bat"

fonts="font-adobe-source-code-pro terminus-font dejavu-fonts-ttf"

rm_services=("agetty-tty4" "agetty-tty5" "agetty-tty6")

en_services=("acpid" "dbus" "chronyd" "cupsd" "NetworkManager" \
"iwd" "sddm" "gdm" "lightdm" "zramen" "grub-btrfs" "dhcpcd")
}

prepdisk()
{
if [[ $uefi == "true" ]]; then
	if [[ $disk == *"sd"* ]]; then
	boot_part=$(echo $disk'1')
	luks_part=$(echo $disk'2')
	elif [[ $disk == *"vd"* ]]; then
	boot_part=$(echo $disk'1')
	luks_part=$(echo $disk'2')
	elif [[ $disk == *"nvme"* ]]; then
	boot_part=$(echo $disk'p1')
	luks_part=$(echo $disk'p2')
	fi
else
	if [[ $disk == *"sd"* ]]; then
	luks_part=$(echo $disk'1')
	elif [[ $disk == *"vd"* ]]; then
	luks_part=$(echo $disk'1')
	elif [[ $disk == *"nvme"* ]]; then
	luks_part=$(echo $disk'p1')
	fi
fi


dialog --yesno "enable disk encryption?" 0 0 --output-fd 1
encryption=$?
clear


if [[ $encryption == 0 ]]; then
	diskmap="/dev/mapper/crypt"
	passwcheck "luks"
	luks_pw=$pw
#	echo $root_pw $user_pw $luks_pw >> teste.txt
else
	diskmap=$luks_part
fi

dialog --yesno "you are about to erase and format the disk, do you want to proceed?" 0 0 --output-fd 1
begin=$?
clear

if [[ $begin == 0 && $disk != "/dev/vda" ]]; then

	dialog --yesno "write urandom data to disk?" 0 0 --output-fd 1
	urd=$?
	if [[ $urd == 0 ]]; then
		dd if=/dev/urandom of=$disk bs=4096 count=5000 status=progress # +- 20G
	fi
fi

if [[ $begin == 0 ]]; then

	#Wipe disk
	wipefs -aqf $disk
else exit
fi

if [[ $uefi == "true" ]]; then
	printf 'label: gpt\n, %s, U, *\n, , L\n' "$boot_part_size" | sfdisk -qf "$disk"
else
sfdisk $disk <<EOF
label: dos
, , L, *
EOF
fi

#Create LUKS2 encrypted partition
#cryptsetup benchmark   to find the best cypher for your pc


if [[ $bm == "grub"  &&  $encryption == 0 ]]; then
	echo $luks_pw | cryptsetup -q luksFormat --type luks1 $luks_part
	echo $luks_pw | cryptsetup open $luks_part crypt
elif [[ $bm == "uki"  &&  $encryption == 0 ]]; then
	echo $luks_pw | cryptsetup -q luksFormat $luks_part #luks2
	echo $luks_pw | cryptsetup open $luks_part crypt
fi


if [[ $fs_type != "btrfs" ]]; then
	vgcreate $hostname $diskmap
fi

if [[ $fs_type != "btrfs" && $root_part_size == "" ]]; then
	lvcreate --name root -l 100%FREE $hostname
	mkfs.$fs_type -qL root /dev/$hostname/root
	mount /dev/$hostname/root /mnt
elif [[ $fs_type != "btrfs" && $root_part_size != "" ]]; then
	lvcreate --name root -L $root_part_size $hostname
	lvcreate --name home -l 100%FREE $hostname
	mkfs.$fs_type -qL root /dev/$hostname/root
	mount /dev/$hostname/root /mnt
	mkfs.$fs_type -qL home /dev/$hostname/home
	mkdir -p /mnt/home
	mount /dev/$hostname/home /mnt/home
fi


if [[ $fs_type == "btrfs" ]]; then
	mkfs.btrfs -L $hostname $diskmap
	BTRFS_OPTS="noatime,compress,space_cache=v2,discard=async,ssd"
	mount -o $BTRFS_OPTS $diskmap /mnt
	btrfs subvolume create /mnt/@
	btrfs subvolume create /mnt/@home
	btrfs subvolume create /mnt/@log
    btrfs subvolume create /mnt/@cache
    btrfs subvolume create /mnt/@snapshots
    umount /mnt
	mount -o $BTRFS_OPTS,subvol=@ $diskmap /mnt
	mkdir -p /mnt/{home,.snapshots,var/log,var/cache}
	mount -o $BTRFS_OPTS,subvol=@home $diskmap /mnt/home
	mount -o $BTRFS_OPTS,subvol=@log $diskmap /mnt/var/log
	mount -o $BTRFS_OPTS,subvol=@cache $diskmap /mnt/var/cache
	mount -o $BTRFS_OPTS,subvol=@snapshots $diskmap /mnt/.snapshots
fi


if [[ $uefi == "true" ]]; then
	boot_part_name="/boot/efi"

	#create efi and boot partition
	mkfs.vfat -F 32 $boot_part
	mkdir -p /mnt$boot_part_name
	mount $boot_part /mnt$boot_part_name
fi


for dir in dev proc sys run; do
	mkdir -p /mnt/$dir
	mount --rbind /$dir /mnt/$dir
	mount --make-rslave /mnt/$dir
done

}

prepsys()
{


mkdir -p /mnt/var/db/xbps/keys
cp /var/db/xbps/keys/* /mnt/var/db/xbps/keys/

if [[ $bm == "uki" && $uefi == "true" ]]; then
	XBPS_ARCH=$ARCH xbps-install -SyR $void_repo -r /mnt base-system binutils zstd cryptsetup lvm2 efibootmgr \
	sbsigntool systemd-boot-efistub sbctl dracut-uefi opendoas \
	runit-void-apparmor runit-nftables apparmor zsh

	chroot /mnt xbps-alternatives -s dracut-uefi

elif [[ $bm = "grub" && $uefi == "true" ]]; then
	XBPS_ARCH=$ARCH xbps-install -SyR $void_repo -r /mnt base-system binutils zstd cryptsetup lvm2 efibootmgr \
	sbctl grub-btrfs grub-btrfs-runit btrfs-progs grub-x86_64-efi opendoas \
	runit-void-apparmor runit-nftables apparmor systemd-boot-efistub ukify zsh

elif [[ $bm = "grub" && $uefi == "false" ]]; then

	XBPS_ARCH=$ARCH xbps-install -SyR $void_repo -r /mnt base-system binutils zstd cryptsetup \
	lvm2 grub-btrfs grub-btrfs-runit btrfs-progs grub opendoas \
	runit-void-apparmor runit-nftables apparmor zsh
fi

#chroot

$crm chown root:root /
$crm chmod 755 /

useradd -R /mnt -m -U -G $user_groups $username -s /bin/zsh

cat << EOF | $crm
echo "$root_pw\n$root_pw" | passwd -q root
echo "$user_pw\n$user_pw" | passwd -q $username
EOF

#set hostname and language/locale
echo $hostname > /mnt/etc/hostname


echo "LANG=$language" > /mnt/etc/locale.conf

$crm ln -sf $local /etc/localtime

echo "$language UTF-8" >>  /mnt/etc/default/libc-locales


luks_root_uuid=$(blkid -o value -s UUID  /mnt/dev/mapper/$hostname-root)
luks_home_uuid=$(blkid -o value -s UUID  /mnt/dev/mapper/$hostname-home)

if [[ $uefi == "true"  ]]; then
	boot_uuid=$(blkid -o value -s UUID  /mnt$disk'1')
	luks_uuid=$(blkid -o value -s UUID  /mnt$disk'2')
else
	luks_uuid=$(blkid -o value -s UUID  /mnt$disk'1')
fi

ROOT_UUID=$(blkid -o value -s UUID $diskmap)



}

hardening()
{
#disable root login
if [[ $adm ==  0 ]]; then
	sed -i 's,^root:x:0:0:root:/root:/bin/bash,root:x:0:0:root:/root:/sbin/nologin,' /mnt/etc/passwd
fi

# harden sysctl

mkdir /mnt/etc/sysctl.d

echo -e "
# Restringe o acesso ao buffer de mensagens do kernel (dmesg) apenas ao root
kernel.dmesg_restrict = 1

# Oculta endereços de ponteiros do kernel em /proc para prevenir exploits de memória
kernel.kptr_restrict = 2

# Restringe o uso de ptrace (evita que um processo intersete ou modifique outro)
kernel.yama.ptrace_scope = 1

# Desativa dumps de memória (core dumps) para binários SUID
fs.suid_dumpable = 0

# Proteção contra ataques de negação de serviço (DoS) via Ctrl-Alt-Del
kernel.ctrl-alt-del = 0

# Ativa a proteção de SYN Cookies para mitigar ataques de SYN Flood
net.ipv4.tcp_syncookies = 1

# Ativa a filtragem de caminho reverso (impede spoofing de IP de origem)
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1

# Ignora redirecionamentos ICMP (previne ataques Man-in-the-Middle)
net.ipv4.conf.all.accept_redirects = 0
net.ipv4.conf.default.accept_redirects = 0
net.ipv6.conf.all.accept_redirects = 0
net.ipv6.conf.default.accept_redirects = 0

# Não envia redirecionamentos ICMP (esta máquina não age como um router)
net.ipv4.conf.all.send_redirects = 0
net.ipv4.conf.default.send_redirects = 0

# Rejeita pacotes com roteamento estático na origem (Source Routing)
net.ipv4.conf.all.accept_source_route = 0
net.ipv4.conf.default.accept_source_route = 0
net.ipv6.conf.all.accept_source_route = 0
net.ipv6.conf.default.accept_source_route = 0

# Ignora pings direcionados ao endereço de broadcast (previne amplificação DoS)
net.ipv4.icmp_echo_ignore_broadcasts = 1

# Regista pacotes suspeitos (como spoofing, pacotes marcados e redirecionamentos)
net.ipv4.conf.all.log_martians = 1
net.ipv4.conf.default.log_martians = 1
" > /mnt/etc/sysctl.d/99-hardening.conf


#doas
echo "permit persist :$username" > /mnt/etc/doas.conf

$crm << EOF
chown -c root:root /etc/doas.conf
chmod -c 0400 /etc/doas.conf
EOF

#ssh / cron hardening permissions
echo -e "
PasswordAuthentication no
PermitRootLogin no
KbdInteractiveAuthentication no
" >> /mnt/etc/ssh/sshd_config

$crm << EOF
chown -c root:root /etc/ssh/sshd_config
chmod -c 0400 /etc/ssh/sshd_config
chown -c root:root /etc/cron.daily
chmod -c 0400 /etc/cron.daily
EOF

#blacklist modules and drivers not needed
echo -e "blacklist dccp
install dccp /bin/false
blacklist sctp
install sctp /bin/false
blacklist rds
install rds /bin/false
blacklist tipc
install tipc /bin/false
blacklist firewire-core
install firewire-core /bin/false
blacklist thunderbolt
install thunderbolt /bin/false" > /mnt/etc/modprobe.d/blacklist.conf

#apparmor

sed -i 's/^#*write-cache/write-cache/i' /mnt/etc/apparmor/parser.conf

}

appsinstall()
{
XBPS_ARCH=$ARCH xbps-install -SuyR $void_repo -r /mnt xbps
XBPS_ARCH=$ARCH xbps-install -SyR $void_repo -r /mnt void-repo-nonfree

if [[ $graphical == "kde" ]]; then
	XBPS_ARCH=$ARCH xbps-install -SyR $void_repo -r /mnt $apps_base $apps_kde $apps_intel $apps_optional $fonts \
	$apps_office $apps_multimedia $apps_browser

elif [[ $graphical == "gnome" ]]; then
	XBPS_ARCH=$ARCH xbps-install -SyR $void_repo -r /mnt $apps_base $apps_gnome $apps_intel $apps_optional $fonts \
	$apps_office $apps_multimedia $apps_browser
elif [[ $graphical == "xfce" ]]; then
	XBPS_ARCH=$ARCH xbps-install -SyR $void_repo -r /mnt $apps_base $apps_xfce $apps_intel $apps_optional $fonts

elif [[ $graphical == "minimal" ]]; then
	XBPS_ARCH=$ARCH  xbps-install -SyR $void_repo -r /mnt $apps_minimal $fonts

fi
}

firewall()
{
#firewall nftables example for a workstation

echo -e '

 #!/usr/sbin/nft -f

flush ruleset

table inet filter {
    chain input {
        type filter hook input priority filter; policy drop;

        # 1. Interface loopback
        iif "lo" accept

        # 2. Conexões já estabelecidas e relacionadas
        ct state established,related accept

        # 3. Descartar pacotes inválidos
        ct state invalid drop

        # 4. Permitir tráfego da interface do virt-manager (libvirt)
        iifname "virbr*" accept

        # 5. ICMP (IPv4) e ICMPv6 (Essencial para IPv6)
        ip protocol icmp icmp type echo-request limit rate 5/second accept
        ip6 nexthdr icmpv6 icmpv6 type { destination-unreachable, packet-too-big, time-exceeded, parameter-problem, echo-request, nd-router-solicit, nd-router-advert, nd-neighbor-solicit, nd-neighbor-advert } accept

        # 6. Permitir SSH (com registo de log)
        # tcp dport 22 log prefix "NFTABLES-SSH: " accept
		# tcp dport 1714-1764 accept comment "accept KDE Connect functionality"
        # udp dport 1714-1764 accept comment "accept KDE Connect functionality"
        # 7. Registar logs de bloqueios
        log prefix "NFTABLES-DROP: " level warn
    }

    chain forward {
        type filter hook forward priority filter; policy drop;

        # Permitir que as VMs acedam à internet e comuniquem entre si
        iifname "virbr*" oifname "virbr*" accept
        iifname "virbr*" accept
        oifname "virbr*" ct state established,related accept
    }

    chain output {
        type filter hook output priority filter; policy accept;
    }
} ' > /mnt/etc/nftables.conf

}

configsys()
{

#fstab
xgenfstab -U /mnt > /mnt/etc/fstab

#set main and nonfree repo

echo "repository=$void_repo" > /mnt/etc/xbps.d/00-repository-main.conf

echo "repository=$void_repo/nonfree" > /mnt/etc/xbps.d/10-repository-main.conf

if [[ $graphical != "minimal" ]]; then

	#pipewire
	$crm mkdir -p /etc/pipewire/pipewire.conf.d
	$crm ln -s /usr/share/examples/wireplumber/10-wireplumber.conf /etc/pipewire/pipewire.conf.d/
	$crm ln -s /usr/share/examples/pipewire/20-pipewire-pulse.conf /etc/pipewire/pipewire.conf.d/

	#start pipewire.desktop for kde gnome etc
	$crm ln -s /usr/share/applications/pipewire.desktop /etc/xdg/autostart/pipewire.desktop

	#octoxbps-notifier
	$crm ln -s /usr/share/applications/octoxbps-notifier.desktop /etc/xdg/autostart/octoxbps-notifier.desktop
fi

#disable services
for serv1 in ${rm_services[@]}; do

	$crm touch /etc/sv/$serv1/down
done

#enable services
for serv2 in ${en_services[@]}; do

	$crm ln -s /etc/sv/$serv2 /var/service

done

#rc.conf
echo -e 'KEYMAP="'$keyb'"
FONT="ter-v22b"' >> /mnt/etc/rc.conf

#time zone
$crm ln -sf $local /etc/localtime

#iwd
	mkdir -p /mnt/etc/iwd

	echo -e "[General]
	EnableNetworkConfiguration=false
	[Network]
	RoutePriorityOffset=200
	NameResolvingService=none" > /mnt/etc/iwd/main.conf
}


custom()
{

echo -e "alias xi='doas xbps-install -S'
alias xu='doas xbps-install -Su'
alias xs='xbps-query -Rs'
alias xr='doas xbps-remove -oOR'
alias xq='xbps-query'
alias xsi='xbps-query -m'
alias sudo='doas'
alias dmesg='doas dmesg'
alias e='nano'
alias de='doas nano'
alias vsv='doas vsv'
alias reboot='doas reboot'
alias poweroff='doas poweroff'
alias ss='ss -tunap'
alias ll='ls -all'
alias sensors='watch sensors'" > /mnt/home/$username/.aliases

$crm chown $username:$username /home/$username/.aliases

#fonts
$crm ln -s /usr/share/fontconfig/conf.avail/70-no-bitmaps.conf /etc/fonts/conf.d/
#xbps-reconfigure -fr fontconfig /mnt/

#ignore packages
$crm touch /etc/xbps.d/99-ignorepkgs.conf

ignore_pkgs=("sudo" "linux-firmware-amd" "linux-firmware-nvidia" "linux-firmware-broadcom" "ipw2100-firmware" "ipw2200-firmware")

for pkg in ${ignore_pkgs[@]}; do
   echo "ignorepkg="$pkg >> /mnt/etc/xbps.d/99-ignorepkgs.conf
   $crm xbps-remove -oOR $pkg -y
done

#zsh

echo -e "
# Histórico de comandos
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory
setopt sharehistory
setopt hist_ignore_dups

# Ativar cores no terminal
autoload -U colors && colors

# Prompt simples e funcional
#PROMPT='%}%F{cyan}%n@%m %F{green}%~ %# %'
PROMPT='%F{green}%n%f@%F{yellow}%m%f:%F{cyan}%~%f$ '



# Ativar auto-completação básica
autoload -U compinit
compinit

# Ativar dicas/completação para comandos do XBPS (se disponível)
#if [ -f /usr/share/zsh/plugins/xbps-command-not-found/xbps-command-not-found.zsh ]; then
#    source /usr/share/zsh/plugins/xbps-command-not-found/xbps-command-not-found.zsh
#fi

ufetch
source .aliases


# Atalhos gerais
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias ll='ls -la'


#if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then
 #   exec startxfce4 --wayland
 #   exec mango
#fi

" > /mnt/home/$username/.zshrc

$crm chown $username:$username /mnt/home/$username/.zshrc

#for autologin with agetty1 add --autologin username to /etc/runit/runsvdir/agetty1/conf
}

bootmanag()
{


#uki
if [[ $bm == "uki" ]]; then
	echo "hostonly=yes" > /mnt/etc/dracut.conf.d/10-boot.conf
	echo 'uefi="yes"'  >> /mnt/etc/dracut.conf.d/10-boot.conf
	echo -e "#!/bin/sh
	mv $boot_part_name/EFI/void/linux-*.efi $boot_part_name/EFI/void/void-signed-uki-old.efi" \
	> /mnt/etc/kernel.d/post-install/10-uefi-boot
	chmod +x /mnt/etc/kernel.d/post-install/10-uefi-boot

	echo -e "#!/bin/sh
	cp $boot_part_name/EFI/void/linux-*.efi $boot_part_name/EFI/void/void-signed-uki.efi" \
	> /mnt/etc/kernel.d/post-install/99-uefi-boot
	chmod +x /mnt/etc/kernel.d/post-install/99-uefi-boot


	echo -e 'CREATE_UEFI_BUNDLES=yes' >> /mnt/etc/default/dracut-uefi-hook

	efibootmgr -c -d $disk -p 1 -L "Void Linux uki OLD" -l "\EFI\void\void-signed-uki-old.efi"
	efibootmgr -c -d $disk -p 1 -L "Void Linux uki" -l "\EFI\void\void-signed-uki.efi"
fi

if [[ $bm == "uki" && $fs_type != "btrfs" ]]; then
	echo 'kernel_cmdline="loglevel=3 rd.luks.name='$luks_root_uuid'=crypt rd.lvm.vg='$hostname' root=/dev/'$hostname'/root rd.luks.allow-discards apparmor=1 security=apparmor"' >> /mnt/etc/dracut.conf.d/10-boot.conf
elif [[ $bm == "uki" && $fs_type == "btrfs" ]]; then
	echo 'kernel_cmdline="loglevel=3 root=UUID='$ROOT_UUID' apparmor=1 security=apparmor"' >> /mnt/etc/dracut.conf.d/10-boot.conf
fi


#GRUB
if [[ $bm == "grub" && $uefi == "true" ]]; then
    $crm grub-install --target=x86_64-efi --efi-directory=$boot_part_name --bootloader-id=Void #	--disable-shim-lock --modules="tpm"

elif [[ $bm == "grub" && $uefi == "false" ]]; then
	$crm grub-install $disk
fi

if [[ $bm == "grub" && $encryption == 0 && $secure_boot == 0 ]]; then
	echo "GRUB_ENABLE_CRYPTODISK=y" >> /mnt/etc/default/grub
elif [[ $bm == "grub" && $encryption == 0 && $secure_boot == 1 ]]; then
	echo "GRUB_ENABLE_CRYPTODISK=y" >> /mnt/etc/default/grub
	dd bs=1 count=64 if=/dev/urandom of=/mnt/boot/volume.key
	$crm chmod 000 /boot/volume.key
	$crm chmod -R g-rwx,o-rwx /boot
	echo 'install_items+=" /boot/volume.key /etc/crypttab "' >> /mnt/etc/dracut.conf.d/10-boot.conf
fi

if [[ $bm == "grub" && $encryption == 0 && $secure_boot == 1 && $uefi == "true" ]]; then
		echo $luks_pw | cryptsetup luksAddKey $disk'2' /mnt/boot/volume.key
elif [[ $bm == "grub" && $encryption == 0 && $secure_boot == 1 && $uefi == "false" ]]; then
		echo $luks_pw | cryptsetup luksAddKey $disk'1' /mnt/boot/volume.key
fi

if [[ $bm == "grub" && $encryption == 0 && $secure_boot == 1 && $fs_type != "btrfs" ]]; then
		echo "crypt UUID=$luks_uuid /boot/volume.key luks" >> /mnt/etc/crypttab
		echo 'GRUB_CMDLINE_LINUX="rd.lvm.vg='$hostname' rd.luks.uuid='$luks_uuid' apparmor=1 security=apparmor"' >> /mnt/etc/default/grub
elif [[ $bm == "grub" && $encryption == 0 && $secure_boot == 1 && $fs_type == "btrfs" ]]; then
		echo 'GRUB_BTRFS_ENABLE_CRYPTODISK="true"' >> /mnt/etc/default/grub-btrfs/config
	    echo "crypt UUID=$ROOT_UUID /boot/volume.key luks" >> /mnt/etc/crypttab
		echo 'GRUB_CMDLINE_LINUX="root=UUID='$ROOT_UUID' apparmor=1 security=apparmor"' >> /mnt/etc/default/grub
fi

if [[ $bm == "grub" && $uefi == "false" && $encryption == 0  && $fs_type != "btrfs" ]]; then
	echo "GRUB_ENABLE_CRYPTODISK=y" >> /mnt/etc/default/grub
    echo 'GRUB_CMDLINE_LINUX="rd.lvm.vg='$hostname' rd.luks.uuid='$luks_uuid' apparmor=1 security=apparmor"' >> /mnt/etc/default/grub
fi


if [[ $bm == "grub" && $uefi == "true" && $secure_boot == 0 ]] ; then

	 cmdline="root=UUID=$ROOT_UUID rw quiet bgrt_disable apparmor=1 security=apparmor"
	 mkdir -p /mnt/etc/kernel
	 echo $cmdline > /mnt/etc/kernel/cmdline


#grub menu for uki
echo -e "menuentry 'Void Linux with UKI (Secure Boot)' --class void --class gnu-linux --class gnu --class os {
    insmod part_gpt
    insmod fat
    search --no-floppy --fs-uuid --set=root $boot_uuid
    chainloader /EFI/void/void-signed-uki.efi
}" >> /mnt/etc/grub.d/40_custom


sed -i 's/^GRUB_DEFAULT=0/GRUB_DEFAULT="Void Linux with UKI (Secure Boot)"/' /mnt/etc/default/grub

fi

if [[ $bm == "grub" ]]; then
	$crm grub-mkconfig -o /boot/grub/grub.cfg
fi

}

secboot()
{
#secure boot
if [[ $secure_boot == 0 ]]; then

	$crm sbctl create-keys
	$crm sbctl enroll-keys -i -m

	echo "SBSIGN_EFI_KERNEL=1" >> /mnt/etc/default/sbsigntool-kernel-hook
	echo "EFI_CERT_FILE=/var/lib/sbctl/keys/db/db.pem" >> /mnt/etc/default/sbsigntool-kernel-hook
	echo "EFI_KEY_FILE=/var/lib/sbctl/keys/db/db.key" >> /mnt/etc/default/sbsigntool-kernel-hook

fi

# if [[ $secure_boot == 0 && $bm == "uki"  ]]; then
#
# 	echo 'uefi_secureboot_cert="/var/lib/sbctl/keys/db/db.pem"' >> /mnt/etc/dracut.conf.d/10-boot.conf
# 	echo 'uefi_secureboot_key="/var/lib/sbctl/keys/db/db.key"' >> /mnt/etc/dracut.conf.d/10-boot.conf
# fi

}

finish()
{
xbps-reconfigure -far /mnt/
}

restart()
{
dialog --yesno "All done! reboot?" 0 0 --output-fd 1
end=$?
clear

if [[ $end == 1 ]]; then
	exit

else
	umount -R /mnt
 	reboot
	shutdown -r now
fi
}

main()
{
starting
prepdisk
prepsys
appsinstall
configsys
hardening
firewall
custom
bootmanag
secboot
finish
}

main

